package com.nextgen.erp.crm.service;
import com.nextgen.erp.crm.domain.model.*; import com.nextgen.erp.crm.dto.*; import com.nextgen.erp.crm.repository.CrmActivityRepository; import lombok.RequiredArgsConstructor; import org.springframework.data.domain.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException; import java.util.UUID;
@Service @RequiredArgsConstructor
public class CrmActivityService {
 private final CrmActivityRepository repo; private final CrmInteractionTargetService targets;
 @Transactional(readOnly=true) public Page<CrmActivity> list(CrmInteractionTargetRequest t,Pageable p){if(t==null)return repo.findAll(p);var x=targets.resolve(t);if(x.getLeadId()!=null)return repo.findByTargetLeadId(x.getLeadId(),p);if(x.getProspectId()!=null)return repo.findByTargetProspectId(x.getProspectId(),p);return repo.findByTargetOpportunityId(x.getOpportunityId(),p);}
 @Transactional(readOnly=true) public CrmActivity get(UUID id){return repo.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Activity not found"));}
 @Transactional public CrmActivity create(CrmActivityRequest r){if(r.getStatus()==com.nextgen.erp.crm.domain.enums.CrmActivityStatus.COMPLETED&&r.getOccurredAt()==null)r.setOccurredAt(java.time.OffsetDateTime.now(java.time.ZoneOffset.UTC));return repo.save(CrmActivity.builder().target(targets.resolve(r.getTarget())).activityType(r.getActivityType()).subject(r.getSubject().trim()).description(r.getDescription()).status(r.getStatus()).occurredAt(r.getOccurredAt()).dueAt(r.getDueAt()).assignedTo(r.getAssignedTo()).build());}
 @Transactional public CrmActivity update(UUID id,CrmActivityRequest r){if(r.getStatus()==com.nextgen.erp.crm.domain.enums.CrmActivityStatus.COMPLETED&&r.getOccurredAt()==null)r.setOccurredAt(java.time.OffsetDateTime.now(java.time.ZoneOffset.UTC));var x=get(id);x.setTarget(targets.resolve(r.getTarget()));x.setActivityType(r.getActivityType());x.setSubject(r.getSubject().trim());x.setDescription(r.getDescription());x.setStatus(r.getStatus());x.setOccurredAt(r.getOccurredAt());x.setDueAt(r.getDueAt());x.setAssignedTo(r.getAssignedTo());return repo.save(x);}
 @Transactional public void delete(UUID id){repo.delete(get(id));}
}
