server:
  port: 8081

spring:
  application:
    name: nextgen-erp-workflow-module
  datasource:
    url: jdbc:postgresql://localhost:5432/nextgen_erp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
