// API client for the NextGen ERP MRP module.
export interface BomItem { id?: string; itemCode: string; itemName: string; qty: number; uom: string; standardRate: number; amount: number; subBomNo?: string; }
export interface BomOperation { id?: string; sequenceNo: number; operationId: string; workstationId: string; timeInMins: number; operatingCost: number; }
export interface Bom { bomNo: string; itemCode: string; itemName: string; quantity: number; uom: string; isActive: boolean; status?: string; revisionNumber?: number; effectiveFrom?: string; effectiveTo?: string; isDefault: boolean; routingId?: string; rawMaterialCost: number; operatingCost: number; scrapCost: number; totalCost: number; items: BomItem[]; operations: BomOperation[]; }
export interface WorkOrderItem { id?: string; itemCode: string; itemName: string; requiredQty: number; transferredQty: number; actualConsumedQty: number; uom: string; standardRate: number; }
export interface WorkOrder { workOrderId: string; parentWoId?: string; productionPlanId?: string; productionItem: string; itemName: string; bomNo: string; qtyToProduce: number; producedQty: number; sourceWarehouse?: string; wipWarehouse?: string; fgWarehouse?: string; plannedStartDate: string; plannedEndDate: string; status: string; plannedMaterialCost: number; actualMaterialCost: number; plannedOperatingCost: number; actualOperatingCost: number; items: WorkOrderItem[]; }
export interface ProductionPlanItem { id?: string; planId: string; itemCode: string; bomNo: string; plannedQty: number; producedQty: number; salesOrderRef?: string; }
export interface ProductionPlan { planId: string; sourceMrpRunId?: string; postingDate: string; status: string; createdBy?: string; createdAt?: string; items: ProductionPlanItem[]; }
export interface MrpRunRequirement { itemCode: string; requiredQty?: number; stockQty?: number; shortageQty?: number; recommendedAction?: string; }
export interface MrpRun { runId: string; bomNo: string; plannedQty: number; planningDate: string; calculationCutoffAt: string; status: string; createdAt: string; requirements: MrpRunRequirement[]; }
export interface InventoryMovement { id: string; itemCode: string; warehouseId?: string; quantity: number; movementType: string; workOrderId?: string; sourceReference: string; createdAt: string; }
export interface StateTransitionAudit { id: string; entityType: string; entityId: string; fromStatus?: string; toStatus: string; action: string; createdAt: string; }
export interface RuntimeDatabaseInfo { databaseName: string; migrationVersion?: string; status: string; }
export interface JobCard { jobCardId: string; workOrderId: string; operationId: string; workstationId: string; forQuantity: number; completedQuantity: number; status: string; assignedEmployeeId?: string; totalTimeInMins: number; scrapQuantity?: number; scrapReason?: string; timeLogs?: any[]; }
export interface OperationItem { operationId: string; operationName: string; defaultWorkstationId?: string; defaultOperatingCost?: number; description?: string; }
export interface RoutingOperation { id?: string; sequenceNo: number; operationId: string; workstationId: string; timeInMins: number; operatingCost?: number; batchSize?: number; }
export interface Routing { routingId: string; routingName: string; itemCode?: string; isActive: boolean; totalOperatingCost?: number; totalRoutingTimeMins?: number; operations: RoutingOperation[]; }

export class MRPApiError extends Error { constructor(public readonly status: number, public readonly code: string, message: string) { super(message); this.name = 'MRPApiError'; } }
const BASE_URL = '/api/v1/mrp';
async function requestJson<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(`${BASE_URL}${path}`, init); const body = await response.json().catch(() => ({})); if (!response.ok) throw new MRPApiError(response.status, body.code || 'API_ERROR', body.message || `MRP request failed (${response.status})`); return body as T; }
const get = <T>(path: string) => requestJson<T>(path);
const post = <T>(path: string, body?: unknown) => requestJson<T>(path, { method: 'POST', ...(body === undefined ? {} : { headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }) });

export const api = {
  getRuntimeDatabase: () => get<RuntimeDatabaseInfo>('/runtime/database'), getBoms: () => get<Bom[]>('/boms'), explodeBom: (id: string) => get<any[]>(`/boms/${encodeURIComponent(id)}/explode`), getWorkOrders: () => get<WorkOrder[]>('/work-orders'), getProductionPlans: () => get<ProductionPlan[]>('/production-plans'), getMrpRuns: () => get<MrpRun[]>('/runs'),
  logMaterialConsumption: (wo: string, itemCode: string, qty: number, key?: string) => { const idempotencyKey = key || globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random()}`; return post<WorkOrder>(`/work-orders/${encodeURIComponent(wo)}/consume?${new URLSearchParams({ itemCode, consumeQty: String(qty), idempotencyKey })}`); },
  getInventoryMovementsForWorkOrder: (id: string) => get<InventoryMovement[]>(`/inventory-movements/work-order/${encodeURIComponent(id)}`), getStateAudit: (type: string, id: string) => get<StateTransitionAudit[]>(`/state-audit/${encodeURIComponent(type)}/${encodeURIComponent(id)}`), getJobCards: () => get<JobCard[]>('/job-cards'),
  completeJobCard: (id: string, qty: number, scrapQty?: number, scrapReason?: string) => { const p = new URLSearchParams({ completedQty: String(qty) }); if (scrapQty) p.set('scrapQty', String(scrapQty)); if (scrapReason) p.set('scrapReason', scrapReason); return post<JobCard>(`/job-cards/${encodeURIComponent(id)}/complete?${p}`); },
  calculateMrpWizard: (bom: string, qty: number, date?: string) => get<any>(`/wizard/calculate?bomNo=${encodeURIComponent(bom)}&plannedQty=${qty}${date ? `&planningDate=${encodeURIComponent(date)}` : ''}`), reviewMrpRun: (id: string) => post<any>(`/runs/${encodeURIComponent(id)}/review`), releaseMrpRun: (id: string) => post<any>(`/runs/${encodeURIComponent(id)}/release`), createProductionPlanFromMrpRun: (id: string) => post<any>(`/runs/${encodeURIComponent(id)}/production-plan`), submitProductionPlan: (id: string) => post<any>(`/production-plans/${encodeURIComponent(id)}/submit`), generateWorkOrdersFromProductionPlan: (id: string) => post<any[]>(`/production-plans/${encodeURIComponent(id)}/generate-work-orders`),
  getQualityInspections: () => get<any[]>('/quality/inspections'), submitQualityInspection: (data: any) => post<any>('/quality/inspections', data), getDowntimeEntries: () => get<any[]>('/downtime'), logDowntime: (data: any) => post<any>('/downtime', data), logScrap: (data: any) => post<any>('/scrap', data), replaceBomItem: (a: string, b: string, c: string, rate?: number) => post<any>(`/boms/replace-item?${new URLSearchParams({ currentItemCode: a, newItemCode: b, newItemName: c, ...(rate === undefined ? {} : { newRate: String(rate) }) })}`), approveBom: (id: string) => post<Bom>(`/boms/${encodeURIComponent(id)}/approve`),
  getMpsSchedules: () => get<any[]>('/mps'), createMpsSchedule: (data: any) => post<any>('/mps', data), submitMpsSchedule: (id: string) => post<any>(`/mps/${encodeURIComponent(id)}/submit`), convertMpsToPlan: (id: string) => post<any>(`/mps/${encodeURIComponent(id)}/to-production-plan`), getSubcontracts: () => get<any[]>('/subcontracting'), createSubcontract: (data: any) => post<any>('/subcontracting', data), dispatchSubcontractMaterials: (id: string) => post<any>(`/subcontracting/${encodeURIComponent(id)}/dispatch-materials`), receiveSubcontractGoods: (id: string) => post<any>(`/subcontracting/${encodeURIComponent(id)}/receive-goods`), getOperations: () => get<OperationItem[]>('/operations'), createOperation: (data: OperationItem) => post<OperationItem>('/operations', data), getRoutings: () => get<Routing[]>('/routings'), createRouting: (data: Routing) => post<Routing>('/routings', data), getWorkOrderById: (id: string) => get<WorkOrder>(`/work-orders/${encodeURIComponent(id)}`), completeWorkOrder: (id: string) => post<WorkOrder>(`/work-orders/${encodeURIComponent(id)}/complete`)
};
